version: 2

updates:
  - package-ecosystem: "github-actions"
    # For GitHub Actions, you do not need to set the directory to /.github/workflows.
    # Configuring the key to / automatically instructs Dependabot to search the /.github/workflows directory, as well as the action.yml / action.yaml file from the root directory.
    # ref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory
    directory: "/"
    schedule:
      interval: "weekly"
