name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  molt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hasundue/molt-action@v1
